version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: php-apache-app
    environment:
      XDEBUG_MODE: debug,develop
      XDEBUG_CONFIG: client_port=9003
    ports:
      - "8765:80"
    volumes:
      - ./:/var/www/html
      - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    depends_on:
      - db
    env_file: [.env]

  db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: ${PMA_HOST}
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  db_data:
