version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-apache-app
    ports:
      - "8765:80"
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
    env_file: [.env]

  db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: ${PMA_HOST}
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  db_data:
